Feature 1
ZabihullahNooriWardak/helloMicroverse pull request #1
Opened 2023-05-30 12:35 UTC by ZabihullahNooriWardak

this is Feature 1 branch

2023-05-30 12:54 UTC, wayungi requested changes
Hi @ZabihullahNooriWardak , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] Add style.css & index.html file 🏁 
- [ ] Added.gitignore file 🏁 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please follow the nstructutions given &  [set up linters](https://github.com/microverseinc/linters-config) in this project. Linters enforce good coding standards. 😄 

- [ ] Your Pul request description is not informative. Please write a brief summary of what you have done in this project under PR description. eg 
```
Add index.html file
Add style. css file
Setup linters 
...

```
- [ ] Your PR title and branch name are not descriptive. Please check out for a new branch and use a more descriptive name and mention the old PR in the new PR. Remember to also give a descriptive PR title.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 12:54 UTC, wayungi commented on README.md
- [x] Please replace this readme file with the [microverse readme template](https://github.com/microverseinc/readme-template) and edit it to match your project 😄

2023-05-30 12:54 UTC, wayungi commented on .gitignore
- [ ] You need to ignore the node_modules folder in your .gitignore file. Please add 
```
node_modules/
```
to your readme. This will ensure that the node modules folder is not pushed to git. 😄

2023-05-30 13:37 UTC, ZabihullahNooriWardak commented on README.md
hey! I do not know this: Your PR title and branch name are not descriptive. Please check out for a new branch and use a more descriptive name and mention the old PR in the new PR. Remember to also give a descriptive PR title. should I create a new branch and repeat all of my work again @wayungi

2023-05-30 22:46 UTC, ZabihullahNooriWardak commented
add index.html
add css.style
configure linter
node_modules/ add to .gitignore file

2023-05-30 23:28 UTC, jmonto55 reviewed
# STATUS: APPROVED 🟢

Hi @ZabihullahNooriWardak , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![AgreeSealGIF](https://user-images.githubusercontent.com/116701485/232347692-8a213af9-b250-4d2c-a690-7f42d3c630e0.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 00:43 UTC, ZabihullahNooriWardak commented
just this featured branched is merged to main or master branch

2023-05-31 00:44 UTC, merged